import {localCommands} from '../src/local-tools.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Store,PRIMARY,DAY } from '../src/store.js';
import * as e from '../src/economy.js';
import { AI,AILimit,cycleInfo } from '../src/ai.js';
import { recordActivity,bucketKeys } from '../src/util.js';
import { sqliteAuth } from '../src/auth.js';
import { card } from '../src/cards.js';
import { convert,platformUrl } from '../src/media.js';
import { Commands,categories } from '../src/commands.js';
import { Scheduler } from '../src/scheduler.js';
import { panel } from '../src/panel.js';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'eddine-test-'));const store=new Store(root);t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true});});return store;}
const A='212600000001',B='212600000002',child='212600000003';
test('durable writes, atomic rollback, isolated accounts and auth keys',t=>{const s=fixture(t);s.change(A,x=>{e.register(x,A,'Alice');});s.change(child,x=>{e.register(x,A,'Other Alice');});assert.equal(s.get(A).users[A].name,'Alice');assert.equal(s.get(child).users[A].name,'Other Alice');assert.throws(()=>s.tx([A,child],x=>{x[A].users[A].wallet=0;throw Error('fail');}));assert.equal(s.get(A).users[A].wallet,200);const auth=sqliteAuth(s,A);auth.state.creds.registered=true;auth.save();assert.equal(sqliteAuth(s,A).state.creds.registered,true);assert.equal(sqliteAuth(s,child).state.creds.registered,false);s.db.exec('PRAGMA wal_checkpoint(FULL)');const reopened=new Store(s.root);assert.equal(reopened.get(A).users[A].wallet,200);reopened.close();});
test('daily/work cooldowns, profession growth, consumables, shields, bank conservation',t=>{const s=fixture(t);s.change(A,x=>{e.register(x,A,'Alice');e.register(x,B,'Bob');e.daily(x,A,10*DAY);assert.throws(()=>e.daily(x,A,10*DAY+100));x.users[A].job='developer';x.users[A].wallet=10000;e.buy(x,A,'laptop');e.use(x,A,'laptop');const before=x.users[A].wallet;const r=e.work(x,A,10*DAY);assert.equal(r.earned,225);assert.equal(x.users[A].wallet,before+225);assert.throws(()=>e.work(x,A,10*DAY+1));e.buy(x,A,'booster');e.use(x,A,'booster');assert.equal(e.work(x,A,10*DAY+1800000).earned,450);e.buy(x,A,'shield');e.use(x,A,'shield');assert.throws(()=>e.rob(x,B,A,Date.now()));const total=x.users[A].wallet+x.users[A].bank;e.bank(x,A,'deposit',500);e.bank(x,A,'withdraw',100);assert.equal(total,x.users[A].wallet+x.users[A].bank);assert.throws(()=>e.bank(x,A,'withdraw',10000));assert.throws(()=>e.amount('-10'));assert.throws(()=>e.amount('1e3'));});});
test('transfer fees reach Salah Eddine across namespaces without minting coins',t=>{const s=fixture(t);s.change(PRIMARY,x=>e.register(x,PRIMARY,'Salah Eddine'));s.change(child,x=>{e.register(x,A,'Alice');e.register(x,B,'Bob');});const result=e.pay(s,child,A,B,100);assert.equal(result.fee,5);assert.equal(result.received,95);assert.equal(s.get(child).users[A].wallet,100);assert.equal(s.get(child).users[B].wallet,295);assert.equal(s.get(PRIMARY).users[PRIMARY].wallet,205);assert.throws(()=>e.pay(s,child,A,B,1000));assert.equal(s.get(child).users[A].wallet,100);assert.throws(()=>e.pay(s,PRIMARY,PRIMARY,PRIMARY,10));});
test('fees collected before owner registration are credited on registration',t=>{const s=fixture(t);s.change(child,x=>{e.register(x,A,'Alice');e.register(x,B,'Bob');});e.pay(s,child,A,B,20);assert.equal(s.get(PRIMARY).pendingFees,1);s.change(PRIMARY,x=>e.register(x,PRIMARY,'Salah'));assert.equal(s.get(PRIMARY).users[PRIMARY].wallet,201);});
test('three-day retention removes states and historical snapshots',t=>{const s=fixture(t);s.status(A,'online');s.ensure(A);s.snapshot();s.unpair(A,1000);s.cleanup(1000+3*DAY-1);assert.ok(s.get(A));s.cleanup(1000+3*DAY);assert.equal(s.get(A),null);assert.ok(!fs.existsSync(path.join(s.root,'backups',A)));});
test('activity day/week rollover preserves total',t=>{const s=fixture(t);s.change(A,x=>{recordActivity(x,'g',B,new Date('2026-10-05T12:00:00Z'));recordActivity(x,'g',B,new Date('2026-10-06T12:00:00Z'));assert.deepEqual(x.activity.g.users[B],{today:1,week:2,total:2});recordActivity(x,'g',B,new Date('2026-10-12T12:00:00Z'));assert.deepEqual(x.activity.g.users[B],{today:1,week:1,total:3});});});
function configure(s,budget=0.02){s.change('host',h=>{h.ai.provider='openai';h.ai.enabled=true;h.ai.key='test-key';h.ai.budgetUsd=budget;});}
test('AI budget stops before network; single persistent limit notice',async t=>{const s=fixture(t);configure(s,0.00001);let calls=0;const ai=new AI(s,{fetcher:async()=>{calls++;throw Error('unexpected');}});await assert.rejects(ai.text('chat','hi',[{role:'user',content:'hi'}]),err=>err instanceof AILimit&&err.notice);await assert.rejects(ai.text('chat','hi',[{role:'user',content:'hi'}]),err=>err instanceof AILimit&&!err.notice);assert.equal(calls,0);assert.equal(s.get('host').ai.spent,0);});
test('AI concurrent requests cannot exceed reserved cap and API errors have no invented reset',async t=>{const s=fixture(t);configure(s,0.001);let calls=0;const ai=new AI(s,{fetcher:async()=>{calls++;return {ok:false,status:429,headers:new Headers(),json:async()=>({error:{code:'insufficient_quota'}})};}});await assert.rejects(ai.request('responses',{},0.0008,'chat'),AILimit);assert.equal(calls,1);assert.equal(s.get('host').ai.blocked.until,null);await assert.rejects(ai.request('responses',{},0.0008,'chat'),err=>err instanceof AILimit&&!err.notice);assert.equal(calls,1);});
test('ambiguous failures retain upper cost; known usage releases unused reservation',async t=>{const s=fixture(t);configure(s,1);const ai=new AI(s,{fetcher:async()=>{throw Error('network');}});await assert.rejects(ai.request('responses',{},0.1,'chat'));assert.equal(s.get('host').ai.spent,0.1);ai.fetch=async()=>({ok:true,json:async()=>({value:1})});await ai.request('responses',{},0.1,'chat',{charge:()=>0.02});assert.ok(Math.abs(s.get('host').ai.spent-0.12)<1e-9);});
test('group AI does not answer a reply between humans',async t=>{const s=fixture(t);const ai=new AI(s,{fetcher:async()=>{throw Error('should not call');}});assert.equal(await ai.addressed({replyOther:true,explicit:false,text:'what do you think?'}),false);assert.equal(await ai.addressed({replyBot:true}),true);});
test('images render and FFmpeg performs real image-to-sticker and sticker-to-image conversion',async t=>{const png=card('Registration complete','Salah',[['Wallet',200]]);assert.ok(png.length>1000);assert.equal(png.subarray(1,4).toString(),'PNG');const webp=await convert(png,'sticker');assert.equal(webp.buffer.subarray(8,12).toString(),'WEBP');const result=await convert(webp.buffer,'image');assert.equal(result.buffer.subarray(1,4).toString(),'PNG');});
test('download URLs exclude private targets and wrong platforms',()=>{assert.equal(platformUrl('https://youtu.be/abc','youtube'),'https://youtu.be/abc');for(const url of ['http://youtu.be/a','https://127.0.0.1/a','https://youtube.com.evil.test/a','https://a:pass@youtube.com/a','https://youtube.com:8080/a'])assert.throws(()=>platformUrl(url,'youtube'));});
function fakeContext(store){store.ensure(A);return {e:{id:A,sock:{},groups:new Map()},chat:'test@g.us',uid:B,isGroup:true,owner:false,sudo:false,host:false,admin:false,botAdmin:false,args:[],arg:'',prefix:'.',m:{key:{id:'m'}},info:{}};}
test('owner, group-admin, sudo and host permissions fail closed',async t=>{const s=fixture(t),commands=new Commands(s,{},new AI(s),'.'),c=fakeContext(s);for(const command of ['kick','promote','public','setname','sudo','unpair','stopbot','blockbot','updatemedia','adminshop']){c.command=command;await assert.rejects(commands.execute(c));}assert.equal(s.get(A).config.public,false);});
test('all advertised commands have an implementation',()=>{const source=fs.readFileSync(new URL('../src/commands.js',import.meta.url),'utf8');for(const cmd of Object.values(categories).flat())assert.ok(source.includes("case '"+cmd+"'")||localCommands.includes(cmd)&&source.includes('if(localCommands.includes(cmd))return this.local(c)'),cmd);});
test('admin purchase rejected by WhatsApp refunds coins',async t=>{const s=fixture(t);s.change(A,x=>{e.register(x,B,'Bob');x.users[B].wallet=25000;x.groups['test@g.us']={adminShop:true};});const c=fakeContext(s);c.botAdmin=true;c.senderRaw=B+'@s.whatsapp.net';c.e.sock.groupParticipantsUpdate=async()=>[{status:'403'}];const commands=new Commands(s,{},new AI(s),'.');await assert.rejects(commands.buyAdmin(c));assert.equal(s.get(A).users[B].wallet,25000);assert.equal(s.get(A).leases.length,0);});
test('local panel authentication and origin checks protect mutations',async t=>{const s=fixture(t);process.env.PANEL_PORT='18997';t.after(()=>delete process.env.PANEL_PORT);const sessions={list:()=>[],entries:new Map()};const ai=new AI(s);const server=await panel({store:s,sessions,ai,root:path.resolve('.'),logs:[],shutdown:()=>{}});t.after(()=>new Promise(r=>server.close(r)));const token=fs.readFileSync(path.join(s.root,'panel-token.txt'),'utf8');let r=await fetch('http://127.0.0.1:18997/api/state');assert.equal(r.status,401);r=await fetch('http://127.0.0.1:18997/api/state',{headers:{Authorization:'Bearer '+token}});assert.equal(r.status,200);const state=await r.json();assert.equal(state.host.ai.key,undefined);r=await fetch('http://127.0.0.1:18997/api/ai',{method:'POST',headers:{Authorization:'Bearer '+token,Origin:'https://evil.test','Content-Type':'application/json'},body:JSON.stringify({enabled:true})});assert.equal(r.status,403);});
test('expired admin lease demotes only the purchased member and survives failed permissions',async t=>{const s=fixture(t);s.change(A,x=>{e.register(x,B,'Bob');x.leases=[{id:'lease1',chat:'g@g.us',user:B,target:B+'@s.whatsapp.net',at:Date.now()-1000,status:'active'}];});let rejected=true,calls=0;const entry={id:A,status:'online',groups:new Map(),sock:{groupParticipantsUpdate:async(chat,targets,action)=>{calls++;assert.equal(action,'demote');assert.deepEqual(targets,[B+'@s.whatsapp.net']);return [{status:rejected?'403':'200'}];}}};const sessions={entries:new Map([[A,entry]]),group:async()=>({participants:[{id:B+'@s.whatsapp.net',admin:'admin'}]}),send:async()=>({})};const commands={adminQueue:{run:fn=>fn()}};const scheduler=new Scheduler(s,sessions,commands);await scheduler.tick();assert.equal(s.get(A).leases[0].status,'pendingRemoval');rejected=false;await scheduler.tick();assert.equal(calls,2);assert.equal(s.get(A).leases.length,0);});
test('uncertain admin promotion reconciles existing role or refunds a failed attempt',async t=>{const s=fixture(t);s.change(A,x=>{e.register(x,B,'Bob');x.users[B].wallet=0;x.leases=[{id:'lease1',chat:'g@g.us',user:B,target:B+'@s.whatsapp.net',at:Date.now()+DAY,status:'promoting'}];});const entry={id:A,status:'online',groups:new Map(),sock:{}};const sessions={entries:new Map([[A,entry]]),group:async()=>({participants:[{id:B+'@s.whatsapp.net',admin:null}]}),send:async()=>({})};const scheduler=new Scheduler(s,sessions,{adminQueue:{run:fn=>fn()}});await scheduler.tick();assert.equal(s.get(A).users[B].wallet,20000);assert.equal(s.get(A).leases.length,0);});
test('host commands sent from the linked number work and generated output cannot loop',async t=>{const s=fixture(t);const sent=[];const entry={id:PRIMARY,sock:{user:{id:PRIMARY+'@s.whatsapp.net'}},groups:new Map()};const sessions={identity:async(e,value)=>value,send:async(e,chat,content)=>{sent.push(content);return {key:{id:'out'}};},active:()=>1};const commands=new Commands(s,sessions,new AI(s),path.resolve('.'));await commands.message(entry,{key:{id:'owner-message',remoteJid:PRIMARY+'@s.whatsapp.net',fromMe:true},message:{conversation:'.public'},messageTimestamp:Math.floor(Date.now()/1000)});assert.equal(s.get(PRIMARY).config.public,true);await commands.message(entry,{key:{id:'owner-message',remoteJid:PRIMARY+'@s.whatsapp.net',fromMe:true},message:{conversation:'.self'}});assert.equal(s.get(PRIMARY).config.public,true);assert.equal(sent.length,1);});
