import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createCanvas,loadImage} from '@napi-rs/canvas';import {runLocal,Collections,localCommands} from '../src/local-tools.js';import {run} from '../src/media.js';import ffmpeg from 'ffmpeg-static';import ffprobe from 'ffprobe-static';
const c=createCanvas(600,400),ctx=c.getContext('2d');ctx.fillStyle='#e8d6b0';ctx.fillRect(0,0,600,400);ctx.fillStyle='#152959';ctx.fillRect(100,80,180,200);ctx.font='48px sans-serif';ctx.fillText('HELLO 123',30,350);const picture=c.toBuffer('image/png');const img={buffer:picture,type:'imageMessage',data:{mimetype:'image/png',fileName:'sample.png'}};
async function capture(op,inputs=[img],options={}){const outputs=[];await runLocal(op,inputs,options,x=>{outputs.push(x);});return outputs;}
test('24 approved commands: neon and circle produce real stickers',async()=>{assert.equal(localCommands.length,24);for(const op of ['csticker','sround']){const [x]=await capture(op,op==='csticker'?[]:[img],{text:'صلاح Eddine'});assert.equal(x.type,'sticker');assert.equal(x.buffer.toString('ascii',8,12),'WEBP');assert.equal((await loadImage(x.buffer)).width,512);}});
test('local photo effects produce changed images without AI',async()=>{for(const op of ['wanted','jail','rip','sketch','remini']){const [x]=await capture(op,[img],{name:'Salah'});assert.equal(x.type,'image');assert.ok(!x.buffer.equals(picture));assert.ok((await loadImage(x.buffer)).width>=400);}});
test('mines updates metadata and preserves animated frame count',async()=>{const {default:mux}=await import('node-webpmux');const [sticker]=await capture('csticker',[],{text:'original'});const [changed]=await capture('mines',[{buffer:sticker.buffer,type:'stickerMessage'}],{author:'Salah',pack:'eddine-MD'});const w=new mux.Image();await w.load(changed.buffer);assert.ok(w.exif.toString().includes('Salah'));const dir=await fs.mkdtemp(path.join(os.tmpdir(),'eddine-anim-'));try{await run(ffmpeg,['-y','-f','lavfi','-i','testsrc=size=64x64:rate=2','-t','1','-c:v','libwebp','-loop','0',path.join(dir,'a.webp')]);const buffer=await fs.readFile(path.join(dir,'a.webp'));const a=new mux.Image();await a.load(buffer);const [out]=await capture('mines',[{buffer,type:'stickerMessage'}],{author:'Salah',pack:'pack'});const b=new mux.Image();await b.load(out.buffer);assert.equal(b.frames.length,a.frames.length);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('QR round-trip with Unicode',async()=>{const [qr]=await capture('qr',[],{text:'salam مرحبا https://example.com'});const [out]=await capture('readqr',[{buffer:qr.buffer,type:'imageMessage'}]);assert.equal(out.text,'salam مرحبا https://example.com');});
test('PDF creation, page rendering and compression produce valid outputs',async()=>{const [pdf]=await capture('topdf',[img,img]);assert.equal(pdf.buffer.subarray(0,5).toString(),'%PDF-');const input={buffer:pdf.buffer,type:'documentMessage',data:{mimetype:'application/pdf',fileName:'a.pdf'}};const pages=await capture('frompdf',[input]);assert.equal(pages.length,2);assert.equal(pages[0].type,'image');const [out]=await capture('compress',[input]);assert.equal(out.buffer.subarray(0,5).toString(),'%PDF-');assert.ok(out.caption);});
test('ZIP preserves bytes and rejects traversal and expanded bombs',async()=>{const inputs=['hello','world'].map((x,i)=>({buffer:Buffer.from(x),type:'documentMessage',data:{fileName:i+'.txt'}}));const [zip]=await capture('zip',inputs);const out=await capture('unzip',[{buffer:zip.buffer,type:'documentMessage'}]);assert.deepEqual(out.map(x=>x.buffer.toString()),['hello','world']);const {default:JSZip}=await import('jszip');const bad=new JSZip();bad.file('../evil.txt','x');await assert.rejects(capture('unzip',[{buffer:await bad.generateAsync({type:'nodebuffer'}),type:'documentMessage'}]),/Unsafe/);const huge=new JSZip();huge.file('big.bin',Buffer.alloc(26*1024*1024));await assert.rejects(capture('unzip',[{buffer:await huge.generateAsync({type:'nodebuffer',compression:'DEFLATE'}),type:'documentMessage'}]),/expanded/);});
test('collections isolate users and remove completed/cancelled files',async()=>{const collect=new Collections();const a={e:{id:'a'},uid:'u',chat:'g'},b={...a,uid:'v'};try{await collect.start(a,'topdf');assert.equal(collect.get(b),undefined);assert.equal(await collect.add(a,img),1);await assert.rejects(collect.add(a,{buffer:Buffer.from('x'),type:'documentMessage'}),/images only/);const dir=collect.get(a).dir;await collect.finish(a,async(op,files)=>{assert.deepEqual(files[0].buffer,picture);});await assert.rejects(fs.access(dir));await collect.start(a,'zip');const cancel=collect.get(a).dir;await collect.cancel(a);await assert.rejects(fs.access(cancel));}finally{await collect.close();}});
test('audio/video conversions are playable with expected timing',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'eddine-av-'));try{const file=path.join(dir,'sample.mp4');await run(ffmpeg,['-y','-f','lavfi','-i','testsrc=size=160x120:rate=12','-f','lavfi','-i','sine=frequency=440:sample_rate=44100','-t','2','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac',file]);const v={buffer:await fs.readFile(file),type:'videoMessage',data:{mimetype:'video/mp4'}};for(const [op,options]of [['tomp3',{}],['tovn',{}],['trim',{start:'00:00',end:'00:01'}],['speed',{speed:2}],['gif',{}],['reverse',{}],['compress',{}],['merge',{}]]){const [out]=await capture(op,op==='merge'?[v,v]:[v],options);const target=path.join(dir,'out');await fs.writeFile(target,out.buffer);const m=JSON.parse(await run(ffprobe.path,['-v','error','-show_format','-show_streams','-of','json',target]));assert.ok(Number(m.format.duration)>0);if(op==='merge')assert.ok(Number(m.format.duration)>=3.9);if(op==='tovn')assert.equal(m.streams[0].codec_name,'opus');if(op==='gif')assert.equal(out.gif,true);}await assert.rejects(capture('speed',[v],{speed:50}),/range/);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('OCR reads bundled English, French and Arabic locally',async()=>{for(const [lang,text,needle]of [['eng','HELLO SALAH 123','SALAH'],['fra','Bonjour Salah','Bonjour'],['ara','مرحبا صلاح','صلاح']]){const {GlobalFonts}=await import('@napi-rs/canvas');GlobalFonts.registerFromPath(path.resolve('assets/fonts/DejaVuSans.ttf'),'Eddine');const canvas=createCanvas(700,160),context=canvas.getContext('2d');context.fillStyle='white';context.fillRect(0,0,700,160);context.fillStyle='black';context.font='50px Eddine';context.fillText(text,20,95);const [out]=await capture('ocr',[{buffer:canvas.toBuffer('image/png'),type:'imageMessage'}],{lang});assert.ok(out.text.includes(needle),lang+': '+out.text);}});
