import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {mentionPerson,namedTagAll,participantMatches} from '../src/mentions.js';import {Store} from '../src/store.js';import {Commands} from '../src/commands.js';import {AI} from '../src/ai.js';import {generateWAMessageContent} from '@whiskeysockets/baileys';
const A='212600000001',B='212600000002',L='123456789012345';
test('named mention uses one native LID for both visible token and protocol metadata',async()=>{
 const state={displayNames:{[B+'@s.whatsapp.net']:{name:'Ahmed'}},users:{}};const p={id:L+':4@lid',phoneNumber:B+'@s.whatsapp.net',resolved:B+'@s.whatsapp.net'};assert.equal(participantMatches(p,B+'@s.whatsapp.net'),true);
 const person=mentionPerson(state,{jid:B+'@s.whatsapp.net',resolved:B+'@s.whatsapp.net',participant:p});assert.equal(person.name,'Ahmed');assert.equal(person.jid,L+'@lid');assert.equal(person.token,'@'+L);const message=namedTagAll('Hello',[person]);assert.equal(message.text,'Hello\n\n• Ahmed — @'+L);assert.deepEqual(message.mentions,[L+'@lid']);const wire=await generateWAMessageContent(message,{});assert.deepEqual(wire.extendedTextMessage.contextInfo.mentionedJid,[L+'@lid']);
});
test('tagall and GIF reactions resolve LID members without putting a phone token against a LID mention',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'eddine-mentions-'));const s=new Store(dir);s.ensure(A);s.change(A,x=>{x.savedContacts={[A+'@s.whatsapp.net']:{name:'Salah'},[B+'@s.whatsapp.net']:{name:'Ahmed'}};});t.after(()=>{s.close();fs.rmSync(dir,{recursive:true,force:true});});const sent=[];const sessions={identity:async(e,id)=>id===L+'@lid'?B+'@s.whatsapp.net':id,send:async(e,chat,content)=>{sent.push(content);return {};}};const bot=new Commands(s,sessions,new AI(s),path.resolve('.'));
 const c={e:{id:A,sock:{}},uid:A,sender:A+'@s.whatsapp.net',senderRaw:A+':7@s.whatsapp.net',chat:'g@g.us',isGroup:true,admin:true,owner:false,sudo:false,host:false,prefix:'.',command:'hug',args:[],arg:'',m:{key:{}},info:{mentionedJid:[B+'@s.whatsapp.net']},participants:[{id:A+'@s.whatsapp.net',resolved:A+'@s.whatsapp.net'},{id:L+'@lid',resolved:B+'@s.whatsapp.net',phoneNumber:B+'@s.whatsapp.net'}]};
 await bot.execute(c);assert.equal(sent[0].caption,'Salah hugged Ahmed.\n\n@'+A+' · @'+L);assert.deepEqual(sent[0].mentions,[A+'@s.whatsapp.net',L+'@lid']);assert.ok(!sent[0].caption.includes('@'+B));
 c.command='tagall';await bot.execute(c);assert.ok(sent[1].text.includes('Ahmed — @'+L));assert.deepEqual(sent[1].mentions,[A+'@s.whatsapp.net',L+'@lid']);c.command='hidetag';await bot.execute(c);assert.equal(sent[2].text,'Group announcement');assert.equal(sent[2].mentions.length,2);
});
