import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../src/store.js';import {Commands} from '../src/commands.js';import {AI} from '../src/ai.js';import {IMAGE_MODEL} from '../src/gemini.js';import {MediaQueue,detectPlatform,platformUrl,download} from '../src/media.js';
const A='212600000001',B='212600000002';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j0ioAAAAASUVORK5CYII=','base64');
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'eddine-tools-'));const s=new Store(root);s.ensure(A);t.after(()=>{s.close();fs.rmSync(root,{recursive:true,force:true});});const sent=[],actions=[];const e={id:A,status:'online',groups:new Map(),sock:{onWhatsApp:async address=>[{exists:true,jid:address}],groupParticipantsUpdate:async(chat,ids,action)=>{actions.push({chat,ids,action});return [{status:'200'}];}}};const sessions={entries:new Map([[A,e]]),identity:async(e,id)=>id,send:async(e,chat,content)=>{sent.push({account:e.id,chat,content});return {};}};const ai=new AI(s);const bot=new Commands(s,sessions,ai,root);const c={e,command:'add',args:[B],arg:B,chat:'group@g.us',isGroup:true,admin:true,botAdmin:true,owner:true,host:false,sudo:false,uid:A,prefix:'.',participants:[],info:{},m:{key:{}}};return {root,s,sent,actions,e,sessions,ai,bot,c};}
test('add enforces group and bot admin permissions, checks membership and reports privacy denial',async t=>{const x=setup(t);x.c.admin=false;await assert.rejects(x.bot.execute(x.c),/admins/);x.c.admin=true;x.c.botAdmin=false;await assert.rejects(x.bot.execute(x.c),/admin/);assert.equal(x.actions.length,0);x.c.botAdmin=true;await x.bot.execute(x.c);assert.deepEqual(x.actions[0].ids,[B+'@s.whatsapp.net']);x.e.sock.groupParticipantsUpdate=async()=>[{status:'403'}];await assert.rejects(x.bot.execute(x.c),/privacy/);x.c.participants=[{id:B+'@s.whatsapp.net',resolved:B+'@s.whatsapp.net'}];await x.bot.execute(x.c);assert.match(x.sent.at(-1).content.text,/already/);});
test('send delivers once only from owned account and cooldown prevents repeats',async t=>{const x=setup(t);x.c.command='send';x.c.arg='hello there '+B;x.c.args=x.c.arg.split(' ');x.c.owner=false;await assert.rejects(x.bot.execute(x.c),/owner/);x.c.owner=true;await x.bot.execute(x.c);assert.deepEqual(x.sent[0],{account:A,chat:B+'@s.whatsapp.net',content:{text:'hello there'}});await assert.rejects(x.bot.execute(x.c),/60 seconds/);x.sessions.entries.set(B,{id:B,status:'online',sock:x.e.sock});x.c.arg='hello | '+A+' | '+B;await assert.rejects(x.bot.execute(x.c),/own paired/);assert.equal(x.sent.filter(x=>x.chat===B+'@s.whatsapp.net').length,1);});
test('Gemini image extracts real bytes, skips thought output and isolates image quota from chat',async t=>{const x=setup(t);x.s.change('host',h=>{h.ai.enabled=true;h.ai.geminiKey='fake-test-key';});const calls=[];x.ai=new AI(x.s,{fetcher:async(url,opts)=>{calls.push({url,body:JSON.parse(opts.body)});return new Response(JSON.stringify({candidates:[{content:{parts:[{thought:true,inlineData:{mimeType:'image/png',data:'bad'}},{inlineData:{mimeType:'image/png',data:png.toString('base64')}}]}}]}));}});assert.deepEqual(await x.ai.image('chat','a cat'),png);assert.ok(calls[0].url.includes(IMAGE_MODEL));assert.deepEqual(calls[0].body.generationConfig.responseModalities,['IMAGE']);for(let i=0;i<4;i++)await x.ai.image('chat','a cat');await assert.rejects(x.ai.image('chat','a cat'),/cap reached/);const a=x.s.get('host').ai;assert.equal(a.spent,0);assert.equal(a.geminiUsage.models[IMAGE_MODEL].count,5);assert.equal(a.geminiUsage.models[a.geminiModel],undefined);});
test('OpenAI image reserves budget before network and rejects malformed output',async t=>{const x=setup(t);x.s.change('host',h=>{h.ai.provider='openai';h.ai.key='fake';h.ai.enabled=true;h.ai.budgetUsd=0.1;});let count=0;const ai=new AI(x.s,{fetcher:async(url,options)=>{count++;assert.ok(url.endsWith('/images/generations'));assert.equal(JSON.parse(options.body).quality,'low');return new Response(JSON.stringify({data:[{b64_json:png.toString('base64')}]}));}});assert.deepEqual(await ai.image('chat','a cat'),png);await assert.rejects(ai.image('chat','a cat'),/Budget reached/);assert.equal(count,1);});
test('filtered Gemini image is reported without sending bogus picture data',async t=>{const x=setup(t);x.s.change('host',h=>{h.ai.enabled=true;h.ai.geminiKey='fake';});const ai=new AI(x.s,{fetcher:async()=>new Response(JSON.stringify({candidates:[{finishReason:'SAFETY'}]}))});await assert.rejects(ai.image('chat','a cat'),/no image/);});
test('media admission fails promptly while busy then recovers after success or failure',async()=>{const q=new MediaQueue();let release;const first=q.run(()=>new Promise(r=>{release=r;}));await Promise.resolve();await assert.rejects(q.run(()=>assert.fail()),/busy/);release(42);assert.equal(await first,42);await assert.rejects(q.run(()=>{throw Error('failed');}),/failed/);assert.equal(await q.run(()=>7),7);});
test('automatic platform detection accepts supported hosts and rejects tricks and local URLs',()=>{for(const [host,kind]of [['youtu.be','youtube'],['fb.watch','facebook'],['x.com','twitter'],['redd.it','reddit'],['pin.it','pinterest'],['vimeo.com','vimeo'],['dai.ly','dailymotion']])assert.equal(detectPlatform('https://'+host+'/video'),kind);for(const url of ['https://127.0.0.1/a','https://youtube.com.evil.test/a','https://user:pass@youtube.com/a','http://youtu.be/a','https://youtu.be:8080/a'])assert.throws(()=>detectPlatform(url));assert.throws(()=>platformUrl('https://youtu.be/a','instagram'));});
test('YouTube video selects MP4 tracks and does not invoke MP3 extraction',{skip:process.platform==='win32'},async t=>{const x=setup(t);fs.mkdirSync(path.join(x.root,'tools'));const trace=path.join(x.root,'calls.jsonl');fs.writeFileSync(path.join(x.root,'tools','yt-dlp'),'#!/usr/bin/env node\nconst fs=require("node:fs"),args=process.argv.slice(2);fs.appendFileSync('+JSON.stringify(trace)+',JSON.stringify(args)+"\\n");if(args.includes("--dump-single-json"))console.log(JSON.stringify({title:"video",duration:20,availability:"public",webpage_url:"https://youtu.be/fixture"}));else fs.writeFileSync(args[args.indexOf("-o")+1].replace("%(ext)s","mp4"),"fixture");\n',{mode:0o700});const r=await download(x.root,'https://youtu.be/fixture','youtube',{audio:false});assert.equal(r.buffer.toString(),'fixture');const args=JSON.parse(fs.readFileSync(trace,'utf8').trim().split('\n')[1]);assert.ok(!args.includes('-x'));assert.ok(args[args.indexOf('-f')+1].includes('bestvideo'));assert.ok(args.includes('--max-filesize'));});

test('image decoding rejects non-image, invalid base64 and oversized provider data',async()=>{const {decodeGeneratedImage}=await import('../src/image-data.js');assert.throws(()=>decodeGeneratedImage(Buffer.from('not an image').toString('base64')));assert.throws(()=>decodeGeneratedImage('bad!'));assert.throws(()=>decodeGeneratedImage('A'.repeat(14*1024*1024+1)));assert.deepEqual(decodeGeneratedImage(png.toString('base64')),png);});
