import makeWASocket,{Browsers,DisconnectReason,jidNormalizedUser} from '@whiskeysockets/baileys';
import pino from 'pino';
import { sqliteAuth, clearAuth } from './auth.js';
import { phone,normalize,wait } from './util.js';
import { PRIMARY } from './store.js';
import { updateSavedContacts } from './owner-style.js';
import { rememberNames } from './mentions.js';
export class Sessions{
 constructor(store,{handler,log=console.log}={}){this.store=store;this.entries=new Map();this.handler=handler;this.log=log;this.closing=false;this.cache=new Map();}
 active(){return [...this.entries.values()].filter(e=>e.desired).length;}
 list(){return this.store.accounts().map(a=>({id:a.id,status:this.entries.get(a.id)?.status||a.status,blocked:!!a.blocked,unpairedAt:a.unpairedAt,config:this.store.get(a.id)?.config}));}
 async start(id,{pair=false}={}){id=phone(id);const existing=this.entries.get(id);if(existing?.desired&&existing.status!=='logged-out'&&existing.status!=='stopped'){if(pair)throw Error('This account is already active or pairing.');return existing;}if(this.store.account(id)?.blocked)throw Error('This account is blocked by the host.');if(this.active()>=10)throw Error('All 10 account slots are occupied.');const e={id,desired:true,status:pair?'pairing':'connecting',attempts:0,sock:null,timer:null,generation:0,queues:new Map(),sent:new Map(),groups:new Map()};this.entries.set(id,e);this.store.ensure(id);this.store.status(id,e.status);try{await this.connect(e,pair);return e;}catch(error){await this.stop(id);throw error;}}
 async connect(e,pair=false){if(this.closing||!e.desired)return;const generation=++e.generation;const auth=sqliteAuth(this.store,e.id);e.auth=auth;const logger=pino({level:'silent'});const sock=makeWASocket({auth:auth.state,logger,browser:Browsers.windows('Chrome'),syncFullHistory:false,shouldSyncHistoryMessage:()=>false,markOnlineOnConnect:false,keepAliveIntervalMs:30000,connectTimeoutMs:30000,generateHighQualityLinkPreview:false,cachedGroupMetadata:async id=>{const c=e.groups.get(id);return c&&Date.now()-c.time<60000?c.value:undefined;},getMessage:async key=>this.cache.get(e.id+':'+key.id)?.message});e.sock=sock;
 sock.ev.on('creds.update',()=>{if(generation===e.generation)auth.save();});
 sock.ev.on('connection.update',u=>{if(generation!==e.generation)return;if(u.connection==='open'){e.status='online';e.attempts=0;this.store.paired(e.id);clearTimeout(e.pairTimeout);this.log('Connected: '+e.id);}if(u.connection==='close'){const status=u.lastDisconnect?.error?.output?.statusCode;auth.save();if(!e.desired||this.closing)return;if(status===DisconnectReason.loggedOut||status===DisconnectReason.badSession){e.status='logged-out';e.desired=false;this.store.status(e.id,e.status);this.log('Link expired: '+e.id+'. Relink in the panel.');return;}e.status='reconnecting';this.store.status(e.id,e.status);const delay=Math.min(60000,2000*2**Math.min(e.attempts++,5));e.timer=setTimeout(()=>this.connect(e).catch(err=>this.log('Connection retry: '+err.message)),delay);}});
 const contacts=items=>{if(generation===e.generation){updateSavedContacts(this.store,e.id,items);rememberNames(this.store,e.id,items.map(c=>({ids:[c.id,c.phoneNumber,c.lid],name:c.notify||c.verifiedName||c.name})));}};sock.ev.on('contacts.upsert',contacts);sock.ev.on('contacts.update',contacts);
 sock.ev.on('groups.update',items=>{for(const g of items)e.groups.delete(g.id);});
 sock.ev.on('group-participants.update',event=>{e.groups.delete(event.id);this.handler?.participants(e,event).catch(err=>this.log('Group event: '+err.message));});
 sock.ev.on('messages.upsert',event=>{if(event.type!=='notify'||generation!==e.generation)return;for(const m of event.messages){if(!m.message||!m.key?.id||!m.key.remoteJid||m.key.remoteJid==='status@broadcast'||m.key.remoteJid.endsWith('@newsletter'))continue;const key=e.id+':'+m.key.id;if(this.cache.has(key))continue;this.cache.set(key,m);if(this.cache.size>1200)this.cache.delete(this.cache.keys().next().value);if(e.sent.has(m.key.id))continue;const chat=m.key.remoteJid;let queue=e.queues.get(chat)||Promise.resolve();queue=queue.then(()=>this.handler?.message(e,m)).catch(err=>this.log('Message handler: '+err.message));e.queues.set(chat,queue);queue.finally(()=>{if(e.queues.get(chat)===queue)e.queues.delete(chat);});}});
 if(pair&&!auth.state.creds.registered){await wait(1600);if(e.generation!==generation||!e.desired)throw Error('Connection changed while requesting pairing.');e.code=await sock.requestPairingCode(e.id);auth.save();this.log('Pairing requested for '+e.id+' (code visible in the panel)');e.pairTimeout=setTimeout(()=>{if(e.status!=='online')this.stop(e.id).catch(()=>{});},180000);return e.code;}
 if(!auth.state.creds.registered&&!pair){await this.stop(e.id);throw Error('Account is not linked. Request a pairing code in the panel.');}
 }
 async send(e,chat,content,options={}){const r=await e.sock.sendMessage(chat,content,options);if(r?.key?.id){this.store.change(e.id,s=>{s.receipts[r.key.id]=Date.now();});e.sent.set(r.key.id,Date.now());if(e.sent.size>600)e.sent.delete(e.sent.keys().next().value);this.cache.set(e.id+':'+r.key.id,r);}return r;}
 async identity(e,value,alternate){value=normalize(value);alternate=normalize(alternate);if(alternate?.endsWith('@s.whatsapp.net'))return alternate;if(value.endsWith('@lid'))return normalize(await e.sock.signalRepository?.lidMapping?.getPNForLID(value)||value);return jidNormalizedUser(value);}
 async group(e,chat){const c=e.groups.get(chat);if(c&&Date.now()-c.time<60000)return c.value;const value=await e.sock.groupMetadata(chat);e.groups.set(chat,{value,time:Date.now()});return value;}
 async stop(id){const e=this.entries.get(id);if(e){e.desired=false;e.generation++;clearTimeout(e.timer);clearTimeout(e.pairTimeout);e.auth?.save();e.sock?.end(undefined);e.status='stopped';}this.store.status(id,'stopped');}
 async unpair(id){const e=this.entries.get(id);if(e?.sock&&e.status==='online'){try{await e.sock.logout();}catch{}}await this.stop(id);clearAuth(this.store,id);this.store.unpair(id);if(e)e.status='unpaired';}
 async resume(){for(const a of this.store.accounts()){if(a.blocked||a.unpairedAt||!['online','connecting','reconnecting'].includes(a.status))continue;try{await this.start(a.id);}catch(e){this.log(e.message);}}}
 async close(){this.closing=true;for(const e of this.entries.values()){e.desired=false;e.generation++;clearTimeout(e.timer);clearTimeout(e.pairTimeout);e.auth?.save();e.sock?.end(undefined);}}
}
